[user]
	name = Riccardo Petraglia
    useConfigOnly = true

[commit]
  gpgsign = true

[include]
    path = "~/.dotfiles/gitconfig/gitconfig_global"

[include]
    path = "~/.dotfiles/gitconfig/gitconfig.personal"

[includeIf "hasconfig:remote.*.url:git@github.com*/**"]
    path = "~/.dotfiles/gitconfig/gitconfig.personal"

[includeIf "hasconfig:remote.*.url:git@gitlab.meteomatics.com*/**"]
    path = "~/.dotfiles/gitconfig/gitconfig.meteomatics"

[gpg]
	program = /opt/homebrew/bin/gpg
