#!/usr/bin/env bash

echo "----- SITUATION AT `date +%y%m%d_%H%M%S` -----" 
echo "-------- NETWORK PROFILES --------"
pks network-profiles 
echo "------------ CLUSTERS ------------"
pks clusters 
echo "----------------------------------"
